onlyBuiltDependencies:
  - core-js
  - core-js-pure

overrides:
  body-parser@<1.20.3: '>=1.20.3'
  http-proxy-middleware@<2.0.7: '>=2.0.7'
  send@<0.19.0: '>=0.19.0'
  serve-static@<1.16.0: '>=1.16.0'
  express@<4.20.0: '>=4.20.0'
  nanoid@<3.3.8: '>=3.3.8'
  path-to-regexp@<0.1.12: '>=0.1.12'
  path-to-regexp@>=4.0.0 <6.3.0: '>=6.3.0'
  path-to-regexp@<0.1.10: '>=0.1.10'
  '@babel/runtime@<7.26.10': '>=7.26.10'
  cookie@<0.7.0: '>=0.7.0'
